# Numpy

In [1]:
import numpy as np
import time

## Day-1

In [3]:
py_list = [1,2,3]
arr = np.array([1,2,3])

print(np.__version__)

print(type(py_list))
print(type(arr))

print("List: ",py_list)
print("numpy array:" ,arr)

1.21.6
<class 'list'>
<class 'numpy.ndarray'>
List:  [1, 2, 3]
numpy array: [1 2 3]


In [13]:
my_num = [0,1,8,7,0,9,5,4,5,8,0]
num_arr = np.array(my_num)
num_arr2 = num_arr * 2

print(num_arr)
print(num_arr2)
print()
print(type(my_num))
print(type(num_arr))

[0 1 8 7 0 9 5 4 5 8 0]
[ 0  2 16 14  0 18 10  8 10 16  0]

<class 'list'>
<class 'numpy.ndarray'>


### print 5 to 10 by array

In [14]:
arrange = [i for i in range(5,11)]
arr = np.array(arrange)
print(arr)

[ 5  6  7  8  9 10]


### name array

In [15]:
name = "rafi"
name_char_list = [char for char in name]
name_arr = np.array(name_char_list)
print(name_arr)

['r' 'a' 'f' 'i']


### list vs array time tasting

In [31]:


#list 
py_list = list(range(1000000))
start = time.time()
py_list = [x*2 for x in py_list]
print("List taken time", time.time() - start)

#array 
numpy_arr = np.arange(1000000)
start = time.time()
numpy_arr = numpy_arr * 2
print("Numpy taken time", time.time() - start)

List taken time 0.19701123237609863
Numpy taken time 0.0030002593994140625


### array dimension

In [4]:
# array list
arr_1D = np.array([1,2,3])
arr_2D = np.array([[1,2,3],[4,5,6]])
arr_3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

#printing arrays
print(arr_1D)
print()
print(arr_2D)
print()
print(arr_3D)


#printing arrays dimension
print()
print(f"{arr_1D.ndim}D")
print(f"{arr_2D.ndim}D")
print(f"{arr_3D.ndim}D")

#printing shape of arrays
print()
print(arr_1D.shape)
print(arr_2D.shape)
print(arr_3D.shape)


#printing size of arrays
print()
print(arr_1D.size)
print(arr_2D.size)
print(arr_3D.size)

#printing zeros array
print()
zero_arr = np.zeros((2,3))
print(zero_arr)

#printing ones array
print()
one_arr = np.ones((2,3))
print(one_arr)

#graph linspace
print()
graph = np.linspace(0,1,5)
print(graph)

[1 2 3]

[[1 2 3]
 [4 5 6]]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

1D
2D
3D

(3,)
(2, 3)
(2, 2, 3)

3
6
12

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[0.   0.25 0.5  0.75 1.  ]


### Day - 1 Practice Problem

In [5]:
#task - 1
arange_arr = np.arange(5,51,5)
print(arange_arr)

[ 5 10 15 20 25 30 35 40 45 50]


In [30]:
#task - 2
upper = np.ones((2,4))
lower = np.zeros((2,4))
arr = np.vstack([upper, lower])
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [26]:
#task - 3
wanting_value = np.linspace(0,100, 10)
print(wanting_value)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [27]:
#task - 4
arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("Shape:",arr.shape)
print()
print("Dimension:",arr.ndim)

Shape: (2, 2, 2)

Dimension: 3


In [23]:
#task - 5
matrix = np.full((3,3), 7, dtype = np.int32)
print(matrix)
print()
print(matrix.dtype)

[[7 7 7]
 [7 7 7]
 [7 7 7]]

int32


## Day - 2

### Indexing in NumPy

In [41]:
# array list
arr_1D = np.array([1,2,3,4,5,6])
arr_2D = np.array([[1,2,3],[4,5,6]])
arr_3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr_1D[2]) # print 3 from 1D array
print(arr_2D[1,2]) # print 6 from 2D array
print(arr_3D[1,1,1]) # print 11 from 3D array

3
6
11


### Slicing in NumPy

In [45]:
print(arr_1D[1:5])
print(arr_2D[1,:2]) 
print(arr_3D[1,1,1:3])

[2 3 4 5]
[4 5]
[11 12]


### Copy and view in numpy

In [46]:
arr = np.array([1,2,3,4,5,6])

copy_arr = arr.copy()
view_arr = arr.view()

arr[0] = 100

print(arr)
print(copy_arr)
print(view_arr)

[100   2   3   4   5   6]
[1 2 3 4 5 6]
[100   2   3   4   5   6]


### Reshaped array in numpy

In [49]:
arr = np.array([1,2,3,4,5,6])

reshape1 = arr.reshape((2,3))

print(arr)
print()
print(reshape1)

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]


In [56]:
#task 1 Day 2

arr = np.arange(1,10)

reshape1 = arr.reshape((3,3))
print(reshape1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [57]:
#task 2 Day 2
arr = np.arange(1,10)
reshape1 = arr.reshape((3,3))

print(reshape1[1][2])

6


In [59]:
#task 3 day 3
arr = np.arange(1,6)

copy_arr = arr.copy()
view_arr = arr.view()

arr[2] = 50

print(copy_arr)
print(view_arr)

[1 2 3 4 5]
[ 1  2 50  4  5]


In [65]:
# task 4 Day 2

arr = np.arange(1, 13)
reshape1 = arr.reshape((3,4))

print(reshape1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [69]:
# task 5 Day 2

arr = np.arange(1, 13)
reshape1 = arr.reshape((3,4))

print(reshape1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Day 1 & 2 Task

In [70]:
#task 1

arr = np.arange(5,51,5)
print(arr)

[ 5 10 15 20 25 30 35 40 45 50]


In [72]:
#task 2

zero_arr = np.zeros((2,4))
one_arr = np.ones((2,4))

print(zero_arr)
print()
print(one_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [73]:
#task 3

arr = np.arange(0,101,10)
print(arr)

[  0  10  20  30  40  50  60  70  80  90 100]


In [75]:
#task 4

arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("shape:",arr.shape)
print(f"Dimension: {arr.ndim}D")

shape: (2, 2, 2)
Dimension: 3D


In [84]:
#task 5
arr = np.full((3,3),7, dtype = np.int32)
print(arr)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [85]:
# task 6
arr = np.arange(1,10)
reshape_arr = arr.reshape((3,3))
print(reshape_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [86]:
#task 7
arr = np.arange(1,10)
reshape_arr = arr.reshape((3,3))

print(reshape_arr[1][2])

6


In [89]:
#task 8

arr = np.arange(1,10)

copy_arr = arr.copy()
view_arr = arr.view()

arr[5] = 30

print("copy: ",copy_arr)
print("view: ",view_arr)


copy:  [1 2 3 4 5 6 7 8 9]
view:  [ 1  2  3  4  5 30  7  8  9]


In [94]:
#task 9
arr = np.arange(1,13)
reshaped = arr.reshape((3,4))
delete_second_row = np.delete(reshaped, 1, axis=0)
print(arr)
print()
print(reshaped)
print()
print(delete_second_row)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3  4]
 [ 9 10 11 12]]


## Day 3

### practicing Day 1 & 2 problem

In [43]:
#task 1
arr = np.arange(1,17)
reshaped = arr.reshape((4,4))
print(reshaped)

#task 2
print()
arr1 = np.vstack([reshaped[0],reshaped[1]])
print(arr1)

#task 3
print()
arr2 = np.vstack([reshaped[1,1:3],reshaped[2,1:3]])
print(arr2)

#task 4 by list
print()
lst = []
for i in range(reshaped.shape[0]):
    for j in range(reshaped.shape[1]):
        if reshaped[i,j] > 8:
            lst.append(reshaped[i,j])          
print(lst)

# task 4 by array
reshaped1 = reshaped[reshaped > 8]
print()
print(reshaped1)

#task 5
print()
print(reshaped[:4,1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[1 2 3 4]
 [5 6 7 8]]

[[ 6  7]
 [10 11]]

[9, 10, 11, 12, 13, 14, 15, 16]

[ 9 10 11 12 13 14 15 16]

[ 2  6 10 14]


### Day 3 topics

In [30]:
reshaped = reshaped[reshaped > 8]
print(reshaped)

[ 9 10 11 12 13 14 15 16]


In [33]:
mat = np.arange(1,17).reshape(4,4)
# প্রতি দুটি row-এ, প্রতি ২টি column-এ element নাও
print(mat)
print()
print(mat[0:4:2, 0:4:2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 1  3]
 [ 9 11]]


In [34]:
mat = np.arange(1,10).reshape(3,3)

f = mat.flatten()  
r = mat.ravel()

mat[0,0] = 99
print("flatten:", f)   # old values
print("ravel:", r)     # reflects change at [0,0]

flatten: [1 2 3 4 5 6 7 8 9]
ravel: [99  2  3  4  5  6  7  8  9]


In [40]:
mat = np.array([[4,2,4],[1,3,2],[5,3,1]])
print("unique:", np.unique(mat))
print("diag:", np.diag(mat))
print()
print(mat)
print()
print(mat.T) #transpose the matrix

unique: [1 2 3 4 5]
diag: [4 3 1]

[[4 2 4]
 [1 3 2]
 [5 3 1]]

[[4 1 5]
 [2 3 3]
 [4 2 1]]


In [42]:
mat = np.arange(1,37).reshape(6,6)
print(mat)
print()
print(mat[::2, ::2])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

[[ 1  3  5]
 [13 15 17]
 [25 27 29]]


### Day 3 Task

In [45]:
#Task 1
# একটি 5x5 matrix তৈরি করো যেখানে মান থাকবে 1 থেকে 25 পর্যন্ত।
# তারপর সেই matrix থেকে diagonal elements বের করে প্রিন্ট করো।

mat = np.arange(1,26).reshape((5,5))

dia_mat = np.diag(mat)
print(dia_mat)

[ 1  7 13 19 25]


In [59]:
#Task 2
# একটি 1D array তৈরি করো: [10, 20, 30, 40]
# তারপর np.diag() ব্যবহার করে diagonal matrix তৈরি করো।

arr = np.array([10, 20, 30, 40])
dia_mat = np.diag(arr)
print(dia_mat)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


In [47]:
#Task 3
# একটি 1D array তৈরি করো: [2, 4, 2, 6, 4, 8, 6, 10]
# np.unique() ব্যবহার করে unique value গুলো বের করো।

arr = np.array([2, 4, 2, 6, 4, 8, 6, 10])
uni_arr = np.unique(arr)
print(uni_arr)

[ 2  4  6  8 10]


In [13]:
#Task 4
# একটি 2D array তৈরি করো যেটা 3x3 আকারের হবে এবং random মান থাকবে।
# তারপর সেই array-কে row-wise sort করো।

np.random.seed(42)
rand_arr = np.random.randint(1,101,9).reshape((3,3))

print("Random array:")
print(rand_arr)
print()
print("Row wise sorted array:")
print(np.sort(rand_arr, axis=1))


Random array:
[[52 93 15]
 [72 61 21]
 [83 87 75]]

Row wise sorted array:
[[15 52 93]
 [21 61 72]
 [75 83 87]]


In [12]:
#Task 5
# একটি array তৈরি করো [7, 3, 5, 2, 9, 5, 3]
# প্রথমে unique মান বের করো,
# তারপর সেটিকে sort করে প্রিন্ট করো।

arr = np.array([7, 3, 5, 2, 9, 5, 3])
result = np.sort(np.unique(arr))
print(result)

[2 3 5 7 9]


## Day 4

In [8]:
#rand()
arr = np.random.rand(3,5)
print(arr)

[[0.79641619 0.18972174 0.12576705 0.74472962 0.23863494]
 [0.67047692 0.90903064 0.32478635 0.05970138 0.1533944 ]
 [0.47794413 0.6260505  0.3163584  0.2363229  0.93191199]]


In [7]:
#randint()
arr = np.random.randint(1,100,(2,5))
print(arr)

[[62 56 13 78 57]
 [68 34 43 31 65]]


In [11]:
#randn()

arr = np.random.randn(3,3)
print(arr)

[[-1.66808951 -0.2755204  -1.9094958 ]
 [ 0.35243175 -0.93049053  0.16246973]
 [-0.93939017  0.59274831 -0.72559064]]


In [25]:
#random.choice()
arr = np.random.choice([1,2,3,4,5,6,7,8,9])
print(arr)

8


In [32]:
#seed()
np.random.seed(0)
print(np.random.rand(3))

np.random.seed(0)
print(np.random.rand(3))


[0.5488135  0.71518937 0.60276338]
[0.5488135  0.71518937 0.60276338]


In [94]:
#problem
student_details = {}
total_mark = {}

stu_num = np.random.randint(1,100,(10,5))
student_name = [f"Student - {i}" for i in range(1,11)]

for i in range(10):
    student_details[student_name[i]] = stu_num[i]
    total_mark[student_name[i]] = sum(stu_num[i])

highest_mark = [f"{k} : {v}" for k,v in total_mark.items() if v == max(total_mark.values())]
lowest_mark = [f"{k} : {v}" for k,v in total_mark.items() if v == min(total_mark.values())]



print(student_details)
print()
print(total_mark)
print()

for student in highest_mark:
    print(f"Highest Mark -> {student}")

for student in lowest_mark:
    print(f"Lowest Mark  -> {student}")


{'Student - 1': array([73, 19, 18, 43, 45]), 'Student - 2': array([99, 76, 88, 71, 79]), 'Student - 3': array([47, 55, 51, 44, 66]), 'Student - 4': array([79,  7, 48, 45, 10]), 'Student - 5': array([ 4, 10, 35, 95,  2]), 'Student - 6': array([39, 79, 81, 95, 51]), 'Student - 7': array([14, 87, 47, 88, 38]), 'Student - 8': array([94, 91, 83, 87,  7]), 'Student - 9': array([75, 44,  2, 74, 91]), 'Student - 10': array([49, 80, 18, 20, 20])}

{'Student - 1': 198, 'Student - 2': 413, 'Student - 3': 263, 'Student - 4': 189, 'Student - 5': 146, 'Student - 6': 345, 'Student - 7': 274, 'Student - 8': 362, 'Student - 9': 286, 'Student - 10': 187}

Highest Mark -> Student - 2 : 413
Lowest Mark  -> Student - 5 : 146


## Day 3

### Topic-wise Focused Task

#### Array Creation & Shape

In [3]:
# Task - 1
# 1. একটি 1D array তৈরি করো যেখানে মান থাকবে 1 থেকে 12 পর্যন্ত।
# 2. সেটিকে 3x4 আকারে রূপান্তর করো।
# 3. shape, ndim, size, dtype প্রিন্ট করো।

arr = np.arange(1,13).reshape((3,4))
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(3, 4)
2
12
int32


#### Slicing & Indexing

In [15]:
# Task - 2
# উপরের 3x4 matrix থেকে:
# 1. দ্বিতীয় row বের করো
# 2. তৃতীয় column বের করো
# 3. ২য় থেকে ৩য় row ও ১ম থেকে ২য় column-এর অংশ বের করো

print(arr)
print()
print(arr[1])
print()
print(arr[:,2])
print()
print(arr[1:3, :2])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[5 6 7 8]

[ 3  7 11]

[[ 5  6]
 [ 9 10]]


#### Conditional Filtering

In [21]:
# উপরের matrix থেকে:
# 1. যেসব মান 5-এর চেয়ে বেশি, সেগুলো বের করো
# 2. যেসব মান 10-এর সমান বা বেশি, সেগুলোর index বের করো

gt5 = arr[arr>5]
gt10 = np.argsort(arr[arr >= 10])

print(gt5)
print(gt10)



[ 6  7  8  9 10 11 12]
[0 1 2]


#### Mathematical Operations

In [32]:
# উপরের matrix নিয়ে:
# 1. প্রতিটি row-এর যোগফল বের করো
# 2. প্রতিটি column-এর গড় বের করো
# 3. সর্বোচ্চ ও সর্বনিম্ন মান ও তাদের অবস্থান বের করো

sum_of_row = np.array([sum(arr[i]) for i in range(len(arr))])
mean_of_col = np.array([np.mean(arr[:,i]) for i in range(len(arr[0]))])

max_value = np.max(arr)
max_value_idx = np.argmax(arr)
min_value = np.min(arr)
min_value_idx = np.argmin(arr)

print(sum_of_row)
print(mean_of_col)
print(max_value_idx,max_value)
print(min_value_idx,min_value)

2
[10 26 42]
[5. 6. 7. 8.]
11 12
0 1


#### Unique, sort and Diagonal

In [41]:
# Task
# 1. একটি 1D array নাও: [2, 4, 4, 6, 8, 6, 2, 10]
# 2. unique মান বের করো এবং sort করে দেখাও
# 3. sorted array থেকে diagonal matrix তৈরি করো

arr = np.array([10, 6, 4, 4,  8, 6, 2])
uni_value = np.unique(arr)
dia_mat = np.diag(uni_value)

print(uni_value)
print()
print(dia_mat)

[ 2  4  6  8 10]

[[ 2  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  6  0  0]
 [ 0  0  0  8  0]
 [ 0  0  0  0 10]]


In [15]:
# Student Performance Tracker
import numpy as np

# Set the random seed for reproducibility
np.random.seed(42)

# Input & Basic Setup
student = int(input("How many students?: "))
subjects = ["Physics", "Chemistry", "Math", "Biology"]
heading_row = ["Student Roll"] + subjects
student_names = [f"Roll-{i+1:<3}" for i in range(student)]

# Create an object-type 2D array to hold data
data = np.empty((student + 1, len(heading_row)), dtype=object)
data[0] = heading_row
data[1:, 0] = student_names

# Fill in random marks (30–100) for each subject
for i in range(1, student + 1):
    for j in range(1, len(heading_row)):
        data[i][j] = np.random.randint(30, 101)

# Show Full Data
print("\nFull Student Data:\n")
print(data)

# Numeric Data Extraction
numeric_data = data[1:, 1:].astype(np.int32)
roll_list = data[1:, 0]

# Total Marks per Student
print("\nTotal Marks per Student:\n")
for i in range(student):
    total = np.sum(numeric_data[i])
    print(f"{roll_list[i]} → {total}")

# Average Marks per Subject
avg_marks = np.mean(numeric_data, axis=0)
print("\nAverage Marks per Subject:")
for i in range(len(subjects)):
    print(f"{subjects[i]}: {avg_marks[i]:.2f}")

# Topper in Each Subject
print("\nTopper in Each Subject:")
topper_indices = np.argmax(numeric_data, axis=0)
for i, idx in enumerate(topper_indices):
    print(f"{subjects[i]} → {roll_list[idx]} ({numeric_data[idx, i]} marks)")

# Students Who Failed (any subject < 40)
print("\nStudents Who Failed in Any Subject:")
failed_flags = np.any(numeric_data < 40, axis=1)
failed_students = roll_list[failed_flags]
if len(failed_students) > 0:
    for name in failed_students:
        print(name)
else:
    print("All students passed")

# Max & Min Marks
max_val = np.max(numeric_data)
min_val = np.min(numeric_data)
max_pos = np.unravel_index(np.argmax(numeric_data), numeric_data.shape)
min_pos = np.unravel_index(np.argmin(numeric_data), numeric_data.shape)

print(f"\nHighest Mark: {max_val} → {roll_list[max_pos[0]]} in {subjects[max_pos[1]]}")
print(f"Lowest Mark: {min_val} → {roll_list[min_pos[0]]} in {subjects[min_pos[1]]}")

How many students?: 10

Full Student Data:

[['Student Roll' 'Physics' 'Chemistry' 'Math' 'Biology']
 ['Roll-1  ' 81 44 90 50]
 ['Roll-2  ' 53 32 51 82]
 ['Roll-3  ' 31 59 67 31]
 ['Roll-4  ' 93 89 50 62]
 ['Roll-5  ' 87 51 78 88]
 ['Roll-6  ' 71 89 44 91]
 ['Roll-7  ' 91 76 91 80]
 ['Roll-8  ' 84 93 32 80]
 ['Roll-9  ' 36 50 68 47]
 ['Roll-10 ' 33 89 43 38]]

Total Marks per Student:

Roll-1   → 265
Roll-2   → 218
Roll-3   → 188
Roll-4   → 294
Roll-5   → 304
Roll-6   → 295
Roll-7   → 338
Roll-8   → 289
Roll-9   → 201
Roll-10  → 203

Average Marks per Subject:
Physics: 66.00
Chemistry: 67.20
Math: 61.40
Biology: 64.90

Topper in Each Subject:
Physics → Roll-4   (93 marks)
Chemistry → Roll-8   (93 marks)
Math → Roll-7   (91 marks)
Biology → Roll-6   (91 marks)

Students Who Failed in Any Subject:
Roll-2  
Roll-3  
Roll-8  
Roll-9  
Roll-10 

Highest Mark: 93 → Roll-4   in Physics
Lowest Mark: 31 → Roll-3   in Physics


In [20]:
arr = np.empty((2,3,2))
print(arr)
print(arr.dtype)

[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]
int64


In [21]:
a = [1, 2, 3]
b = np.array(a)
c = np.asarray(a)

print(b)
print(c)

print(b is c)

[1 2 3]
[1 2 3]
False


In [23]:
a = np.array([10, 20, 30])
b = np.asarray(a)

print(a)
print(b)

print(a is b)

[10 20 30]
[10 20 30]
True


In [50]:
np.random.seed(2)
new_arr = np.random.randint(1,100,12).reshape(4,3)
print(new_arr)
print()
ones_arr = np.ones_like(new_arr)
print(ones_arr)

[[41 16 73]
 [23 44 83]
 [76  8 35]
 [50 96 76]]

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [57]:
numarics_string = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
print(numarics_string.dtype)

#numarics_string.astype(np.float)
#print(numarics_string.dtype)

|S4


## Project: Student Result Analysis System
### Features:
* Student এর নাম ও subject-wise mark randomly assign হবে

* Total, Average, Max, Min result বের করবে

* Highest scorer কে identify করবে

* Fail করা subject count করবে

* Subject-wise topper ও average দেখাবে

* Filtering: যাদের average 80+ তারা "Scholarship"

* Custom student search by index

* Bonus: Graph বানাতে পারো (later with matplotlib)

### Concepts Used:
* np.array(), np.arange(), reshape(), randint(), astype()

* Indexing, slicing, condition-based filtering

* np.mean(), np.sum(), np.max(), np.min(), argmax(), argwhere(), where(), unravel_index(), unique()

* Broadcasting & dtype handling

### EXPECTED OUTPUT

    How many students?: 3

    🎓 Marks Matrix:
    [[74 77 97 67]
     [85 40 55 41]
     [43 89 96 96]]

    📊 Total Marks per Student:
    [315 221 324]

    📈 Average Marks per Student:
    [78.75 55.25 81.  ]

    📘 Subject-wise Average Marks:
    Math: 67.33
    Physics: 68.67
    Chemistry: 82.67
    Biology: 68.00

    🏆 Highest Scorer: Roll-3 with 324 marks
    😓 Lowest Scorer: Roll-2 with 221 marks

    ❌ Number of Failing Subjects per Student:
    Roll-1: 0 failed subjects
    Roll-2: 2 failed subjects
    Roll-3: 0 failed subjects

    🥇 Topper in each Subject:
    Math Topper: Roll-2 with 85
    Physics Topper: Roll-3 with 89
    Chemistry Topper: Roll-3 with 96
    Biology Topper: Roll-3 with 96

    🎖️ Scholarship Eligible Students:
    Roll-1 with avg 78.75
    Roll-3 with avg 81.00

    🔍 Search Student Marks
    Enter student index (1-based): 2
    Roll-2 - Marks: [85 40 55 41]
    Total: 221, Avg: 55.25

In [11]:
#lets start 
import numpy as np

np.random.seed(42)

total_students = int(input("How many student on the class? : "))
subjects = ["Physics","Chemistry","Math", "Biology","ICT"]
roll_list = np.array([f"Roll - {i+1}" for i in range(total_students)])
marks = np.random.randint(20,101, size = (total_students, len(subjects)))

print("\n-----Mark Matrix-----")
print(marks)

print("\n--Total Mark by subject--")
print(np.sum(marks, axis=0))

print("\n--Avarage Marks Per Students--")
print(np.mean(marks, axis=1))

print("\n--Subject Wise Avarage Number--")

for i in range(len(subjects)):
    print(f"{subjects[i-1]:<10} -> "+ f"{np.mean(marks[i-1], axis=0)}")


How many student on the class? : 12

-----Mark Matrix-----
[[ 71  34  91  80  40]
 [ 94  94  43  22  41]
 [ 72  21  49  57  21]
 [ 83  79  40  52  95]
 [ 77  41  68  78  61]
 [ 79  99  34  81  81]
 [ 66  81  70  74  83]
 [ 22  70  26  40  92]
 [ 58  37  23  79  33]
 [ 28  72  21  79  90]
 [ 63  27  66  54  97]
 [100  55  69  23  21]]

--Total Mark by subject--
[813 710 600 719 755]

--Avarage Marks Per Students--
[63.2 58.8 44.  69.8 65.  74.8 74.8 50.  46.  58.  61.4 53.6]

--Subject Wise Avarage Number--
ICT        -> 53.6
Physics    -> 63.2
Chemistry  -> 58.8
Math       -> 44.0
Biology    -> 69.8


How many students?: 10

Full Student Data:

[['Student Roll' 'Physics' 'Chemistry' 'Math' 'Biology']
 ['Roll-1  ' 81 44 90 50]
 ['Roll-2  ' 53 32 51 82]
 ['Roll-3  ' 31 59 67 31]
 ['Roll-4  ' 93 89 50 62]
 ['Roll-5  ' 87 51 78 88]
 ['Roll-6  ' 71 89 44 91]
 ['Roll-7  ' 91 76 91 80]
 ['Roll-8  ' 84 93 32 80]
 ['Roll-9  ' 36 50 68 47]
 ['Roll-10 ' 33 89 43 38]]

Total Marks per Student:

Roll-1   → 265
Roll-2   → 218
Roll-3   → 188
Roll-4   → 294
Roll-5   → 304
Roll-6   → 295
Roll-7   → 338
Roll-8   → 289
Roll-9   → 201
Roll-10  → 203

Average Marks per Subject:
Physics   : 66.00
Chemistry : 67.20
Math      : 61.40
Biology   : 64.90

Topper in Each Subject:
Physics    → Roll-4   (93 marks)
Chemistry  → Roll-8   (93 marks)
Math       → Roll-7   (91 marks)
Biology    → Roll-6   (91 marks)

Students Who Failed in Any Subject:
Roll-2  
Roll-3  
Roll-8  
Roll-9  
Roll-10 

Highest Mark : 93 → Roll-4   in Physics
Lowest Mark  : 31 → Roll-3   in Physics
